apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  title: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: 7K-Hiroba/${{ values.name }}
  tags:
    - go
    - microservice
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
